### ISSUE TITLE
Error when selecting either option

### ISSUE THREAD

**Issue by bolohori** [flyntwp/generator-flynt#26]
Hello. Managed to install the generator, it starts when I use yo @flyntwp/generator, but whenever I select an option, the following error occurs. Tried running it in the theme folder, in the Components folder and in a newly created folder for a Component.

```console
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, scandir '{myfolder}\themes\flynt\theme\/Components'
    at Object.readdirSync (fs.js:786:3)
    at module.exports._promptComponentFile (C:\Users\bolohori\AppData\Local\Yarn\Data\global\node_modules\@flyntwp\generator-flynt\generators\component\index.js:77:8)
    at prompt.then.answers (C:\Users\bolohori\AppData\Local\Yarn\Data\global\node_modules\@flyntwp\generator-flynt\generators\component\index.js:43:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\bolohori\AppData\Local\Yarn\Data\global\node_modules\yeoman-generator\lib\index.js:450:18)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Cheers !

**Comment by Qakulukiam** [comment]
Hey @bolohori,

thank you for creating this issue!

Unfortunately, the Generator is currently not up to date with the latest version of the Flynt Theme. Some of the file contents and formats in components have changed and are not yet reflected in the generator. We are currently working on fixing this.

The issue you posted about seems to be Windows related. We will take a look and most likely push an update together with the adjustments for the latest theme version.

Best Regards
